[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[context.production.environment]
  HUGO_VERSION = "0.81.0"
  NODE_VERSION = "12.2.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/post"
  status = 302
  force = true

[[headers]]
  for = "/img/*"
  [headers.values]
    cache-control = '''
    public
    max-age=604800'''
