baseurl         = "/"
languageCode    = "de-DE"
paginate        = 15
canonifyurls    = true
assetDir = "static/assets"
enableRobotsTxt = true

[params]
  title       = ""
  subtitle    = ""
  copyright   = "© 2018"

  cover       = "/img/headers/yellow.jpg"
  description = "Music, Art, Dance, Create"
  metaDescription = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "GenerationYProduction"
  ytName = "channel/UC327_c21E-o3c7Ysm0wfpig"
  scName = "generationy_official"
  instagramName = "generation_y_production"

  logo = ""
  orgName = "Generation Y"
  orgWebsite = "https://generation-y.acid.wtf/"
  orgDescription = "Music, Art, Dance, Create"

  showSupport = false

  author = ""
  authorAvatar = ""
  authorLocation = "Munich, Germany"
  authorWebsite = "https://generation-y.acid.wtf/"
  authorDescription = "Music, Art, Dance, Create"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Blog"
  url = "/post"
  weight = 200

[[menu.main]]
  name = "Releases"
  url = "/releases/"
  weight = 105

[[menu.main]]
  identifier = "artists"
  name = "Artists"
  url = "/artists/"
  weight = 100

[[menu.main]]
  identifier = "genres"
  name = "Genres"
  url = "/genres/"
  weight = 50

