backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: title
    fields: # The fields each document in this collection have
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Linktitle", name: "linktitle", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "FooterImage", name: "footerImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "artist" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artist" # Used in the UI, ie.: "New Post"
    folder: "site/content/artists" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    fields: # The fields each document in   this collection have
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Portrait", name: "portrait", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "release" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Release" # Used in the UI, ie.: "New Post"
    folder: "site/content/releases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: title
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Release Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "FooterImage", name: "footerImage", widget: "image", required: false}
      - label: "Artist"
        name: "artist"
        widget: "relation"
        collection: "artist"
        search_fields: ['name']
        value_field: "{{name}}"
        display_fields: ["{{name}}"]  
      - label: "Genre"
        name: "genre"
        widget: "relation"
        collection: "genre"
        search_fields: ['name']
        value_field: "{{name}}"
        display_fields: ["{{name}}"]
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "genre" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Genre" # Used in the UI, ie.: "New Post"
    folder: "site/content/genres" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "color1", name: "color1", widget: "color", required: false}
      - {label: "color2", name: "color2", widget: "color", required: false}
      - {label: "color3", name: "color3", widget: "color", required: false}
      - {label: "color4", name: "color4", widget: "color", required: false}
